
server:
  port: 8181

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/auth?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : huwenhu
    driverClassName : com.mysql.jdbc.Driver
    platform: mysql
    schema: classpath:/schema.sql
    initialization-mode: embedded

  freemarker:
    template-loader-path=classpath: /templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

mybatis :
  config-location : classpath:/mybatis-config.xml

# JWT
jwt:
  header: jwt-token
  secret: mySecret
  #token有效期一天(秒)
  expiration: 86400
  tokenHead: "Bearer_"